[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Restro"
authors = [{name = "Dhiraj", email = "2001dhirajjadhav@gmal.com"}]
dynamic = ["version", "description"]
